#spring:
#  datasource:
#    driverClassName: oracle.jdbc.driver.OracleDriver
#    url:  jdbc:oracle\:thin\:@localhost\:1521\:orcl
#    username: zero
#    password: zero
#    type:  com.alibaba.druid.pool.DruidDataSource
#    mvc:
#      view:
#        prefix: /WEB-INF/jsp/
#        suffix: .jsp
#
#mybatis:
#  type-aliases-package: com.zero.vo
#  mapper-locations: classpath:z/mapper/*.xml